### ISSUE TITLE
nodemon not working

### ISSUE THREAD

**Issue by hemratna** [nestjs/javascript-starter#16]
I am trying to run `npm run start:dev` and getting below error.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1333346/65577944-799c0c80-df92-11e9-8280-4cc9c41e004c.png">

I am trying on 
Node Version: v10.7.0
NPM version: 6.1.0

**Comment by hemratna** [comment]
By adding in dev dependencies
`"@babel/runtime": "^7.6.2"`
`"@babel/plugin-transform-runtime": "^7.6.2",`

`npm run start:dev` wroks fine.

If possiable can we please add in repo?

**Comment by kamilmysliwiec** [comment]
Fixed. Thanks for reporting!
