### ISSUE TITLE
Not working out of the box with @nestjs/mongoose

### ISSUE THREAD

**Issue by ToolReaz** [nestjs/javascript-starter#23]
## Steps to reproduces
- Create new project ``nest n -l js myproject``
- Follow the steps described here: https://docs.nestjs.com/techniques/mongodb 
- ``npm run start:dev``

Then I get this error:
> Support for the experimental syntax 'classProperties' isn't currently enabled 
> Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

## How to fix it
- ``npm install --save-dev @babel/plugin-proposal-class-properties``
- Add ``["@babel/plugin-proposal-class-properties"]`` in the plugins array in ``.babelrc``

Hope this can help :)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? This might be just a temporary solution though, class properties are now in Stage 3 and should be added to the language very shortly.
