### ISSUE TITLE
How to build for production

### ISSUE THREAD

**Issue by chatchaisi** [nestjs/javascript-starter#26]
I use nestjs/javascript-starter but I don't know to to build dist for run in production ?

Thank you

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by shotforsky** [comment]
Here is a solution incase it helps:

> 1. Add `@babel/cli` as a dependency by running `npm install @babel/cli`.
> 2. In the `package.json` file move `@babel/plugin-transform-runtime` and `@babel/runtime` from `devDependencies` to `dependencies`.
> 3. Finally in the `package.json` file add a new script called `build` that runs `babel src -d dist`.

quoated from  https://northflank.com/guides/deploy-nest-js-with-javascript-on-northflank
