### ISSUE TITLE
javascript?

### ISSUE THREAD

**Issue by dknell** [nestjs/javascript-starter#9]
I'm following the docs to try out nest and I've not jumped on the typescript bandwagon just yet, but I was under the impression that this repo would contain standard js code... Is this the right place to start for someone not using typescript? The files in `src` have .js extensions but the code is still typescript.

**Comment by aleivc** [comment]
MarkDown，Surround code with :+1:

**Comment by aleivc** [comment]
markdown, surround code with 
```
<code></code>
```

**Comment by kamilmysliwiec** [comment]
> The files in src have .js extensions but the code is still typescript.

It's not typescript, but rather es6 & es7 JS.
